### ISSUE TITLE
AstroConda IRAF version numbering

### ISSUE THREAD

**Issue by jehturner** [astroconda/astroconda-iraf#2]
The version number of our conda IRAF is currently `2.16.UR`. Apart from adding `.UR` (and using `2.16.1` by mistake for a while), we have never changed the upstream version number in either Ureka or AstroConda, partly because we haven't distributed it as a stand-alone package for that long.

It looks like we now have one or two patches coming up. One is a trivial fix for a bug that breaks `pyraf` on Python 3. We were also [discussing whether to update cfitsio in iraf](https://github.com/astroconda/astroconda-contrib/issues/322) for the security patch also summarized [here](https://github.com/iraf/iraf-v216/issues/134).

Shall we call the next update `2.16.UR.1`? An alternative is just to increment the build number, given the history of IRAF not being versioned properly anyway, but adding a minor version is probably better. 

Note that [conda's documentation](https://conda.io/docs/user-guide/tasks/build-packages/package-spec.html#package-match-specifications) mentions PEP-440 (in connection with comparison operators), which would appear to disallow the use of `.UR`. It's unclear whether conda itself intends such a constraint, but our usage works now and I'm not sure how to avoid using arbitrary letters without changing the package name, given a need to distinguish our patches from the upstream version number.

**Comment by jehturner** [comment]
Just making sure @jhunkeler, @rendinam are copied...

**Comment by olebole** [comment]
@jehturner 
> One is a trivial fix for a bug that breaks pyraf on Python 3.

Can you say more about that or point me to the patch? It may be useful to add it to the Debian IRAF version as well...

**Comment by jehturner** [comment]
Hi Ole. I just changed `task	$ccdtest	= ccdtest$ccdtest.cl` to `task	ccdtest.pkg	= ccdtest$ccdtest.cl` in `ccdred.cl` and added a trivial `ccdtest/ccdtest.par` file that contains this:
```
version,s,h,"2.16.UR"
```
For some reason CL and PyRAF on Python 2 seem to tolerate the fact that a task is used as a package without being declared as one, while on Python 3 it fails (which it shouldn't, but still...). Just adding `pkg` got it to work, but I don't think it's intended that packages should be declared as foreign tasks.

**Comment by olebole** [comment]
Thank you for the explanation, @jehturner!
