### ISSUE TITLE
problem installing iraf with conda

### ISSUE THREAD

**Issue by CoolingFlow** [astroconda/astroconda-iraf#6]
Hi, i'm trying to install the iraf27 enviroment trough the command 

conda create -n iraf27 python=2.7 iraf-all pyraf-all stsci

but i got this: 
Preparing transaction: done
Verifying transaction: done
Executing transaction: - ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package 'http://ssb.stsci.edu/astroconda::iraf.adccdrom-2013_01_02-1'.
LinkError: post-link script failed for package http://ssb.stsci.edu/astroconda::iraf.adccdrom-2013_01_02-1
running your command again with `-v` will provide additional information
location of failed script: /home/diego/anaconda3/envs/iraf27/bin/.iraf.adccdrom-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'http://ssb.stsci.edu/astroconda::iraf.adccdrom-2013_01_02-1'.
LinkError: post-link script failed for package http://ssb.stsci.edu/astroconda::iraf.adccdrom-2013_01_02-1
running your command again with `-v` will provide additional information
location of failed script: /home/diego/anaconda3/envs/iraf27/bin/.iraf.adccdrom-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package http://ssb.stsci.edu/astroconda::iraf.adccdrom-2013_01_02-1
running your command again with `-v` will provide additional information
location of failed script: /home/diego/anaconda3/envs/iraf27/bin/.iraf.adccdrom-post-link.sh
==> script messages <==
<None>

what could it be? what can i do? i have ubuntu 18.04 recently installed and i have anaconda with python 3.7

**Comment by jehturner** [comment]
Hello. I'm just testing a fix for this, assuming it's the same problem reported previously (sounds like it).

**Comment by jehturner** [comment]
If you want, you can add the channel http://astroconda.gemini.edu/testing and try the installation again (you might want to remove that channel afterwards, so you don't pick up test versions in future). I think we can also update the main channel with these new package builds soon, at which point you would just need to try again.

**Comment by qezlou** [comment]
Hi @jehturner  I had exactly the same problem. After adding the test channel you provided above and trying once more the problem solved.
My Os: Fedora (latest version)

**Comment by jehturner** [comment]
This should have been closed when the new packages were published (thanks).
